#!/usr/bin/ksh
# add swap space ,default 2g to centos6/7

# 2G
dd if=/dev/zero of=/var/swapfile bs=1024 count=2048000

# check 
du -ah /var|grep “swapfile”

# make swap
mkswap /var/swapfile
# swap on
swapon /var/swapfile


echo "add to startup
echo "/var/swapfile swap swap defaults 0 0" >> /etc/fstab
