#!/bin/bash
# import passwords file to mysql
cat www.net.sql| grep '#' | awk -F ':' {'print $0'} | awk -F '#' {'print $1,$2,$3'} | sed 's/^/"/' |sed 's/   /","/g' |sed 's/\r$/"/'  > www.sql 


	www.net.sql
	----------------
	123 : xxx  xxxpass xxx@qq.com
	...
	----------------


	conmysql.sh
	---------------
	#!/bin/bash
	filename=www.sql
	#t=1	
	# `1 6428632`
	while read line
	do
		### echo $line
 		li=`echo $line | awk -F ':' {'print $0'} | awk -F '#' {'print $1,$2,$3'} | sed 's/^/"/' |sed 's/   /","/g' |sed 's/\r$/"/'`
		#echo $li
		mysql -uusername -ppassword -e "insert into passdw.www values ('',$li);"

		###  if insert unsuccessed ,log it.
		if [ $? -eq 0 ]
		then
			:
		else
			echo $line >>  special_orign.log	### store failed lines content
			echo $li >>  special_dealed.log		### store failed lines content which being transfered
		fi
		### for execute quickly,un use thisecho
		### echo "$t  done ...";	t=`expr $t + 1`
	done < $filename
	echo 'Done!'
	---------------
	
	
sh conmysql.sh    2>&1 |tee  import.log     ###Output && Redirect to files together
#end of file 


###
##!1 readfile line by line 
while read line
do
      echo $line     
done < filename	

##!2
cat filename| while read line    
do
    echo $line
done

##!3
for line in `cat filename` 
do 
    echo $line 
done 
